### ISSUE TITLE
Enable `formatOnSave` in VS Code

### ISSUE THREAD

**Issue by SailReal** [bb30/de.htwg.se.SudokuInScala#1]
For the start, reformatted code using `scalafmt` in https://github.com/bb30/de.htwg.se.SudokuInScala/commit/f7ec623a113ebb7ad485a0db45d0f8ff0a442a73.

Now we should make sure, that the code will stay formatted, we can archive that using the `formatOnSave`- feature in VS Code: https://stackoverflow.com/a/39973431/825532

**Comment by DonatJR** [comment]
Unfortunately, formatOnSave does not work with the scala formatter plugin. I had this option activated the whole time :/

**Comment by SailReal** [comment]
On my system it is working fine 😂
